import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from '@/providers/SessionProvider'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import ThemeProvider from '@/providers/themeProvider'
import { ThemeProvider as NextThemeProvider } from 'next-themes'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import { TokenProvider } from '@/context/tokenContext'
import ReduxProvider from '@/providers/ReduxProvider'
import { RefreshProvider } from '@/context/RefreshContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Next JS',
    description: 'Generated by Nahid Hasan',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={inter.className}>
                <ReduxProvider>
                    <NextThemeProvider defaultTheme="dark">
                        <AppRouterCacheProvider options={{ key: 'css' }}>
                            <SessionProvider>
                                <TokenProvider>
                                    <ThemeProvider>
                                        <RefreshProvider>
                                            <div className="container">
                                                {children}
                                                <ToastContainer />
                                            </div>
                                        </RefreshProvider>
                                    </ThemeProvider>
                                </TokenProvider>
                            </SessionProvider>
                        </AppRouterCacheProvider>
                    </NextThemeProvider>
                </ReduxProvider>
            </body>
        </html>
    )
}
